import Link from 'next/link';
import Image from 'next/image';
import { getTranslations } from 'next-intl/server';
import { ArrowLeft, ArrowUpRight, Facebook, Instagram, MapPin, Phone, Mail, MessageCircle, Navigation } from 'lucide-react';
import { empresa, enlaceCorreo, enlaceWhatsApp } from '@/lib/empresa';
export async function generateMetadata() { const t = await getTranslations('Navegacion'); return {title: t('contacto')}; }
export default async function Contacto() {
  const t = await getTranslations('Inicio'); const marca = await getTranslations('Marca'); const n = await getTranslations('Navegacion'); const c = await getTranslations('ContactoPagina'); const contacto = await getTranslations('Contacto');
  return <main id="contenido"><section className="contenedor seccion contacto-pagina"><div className="area-ruta"><Link href="/"><ArrowLeft size={14}/>{n('volver')}</Link></div><p className="etiqueta">{t('contactoEtiqueta')}</p><h1>{t('contactoTitulo')}</h1><p className="area-descripcion">{t('contactoTexto')}</p><div className="contactos-grid"><a href={enlaceWhatsApp(contacto('mensaje'))} target="_blank" rel="noopener noreferrer"><MessageCircle/><strong>{c('whatsapp')}</strong><span>{c('escribir')}<ArrowUpRight size={16}/></span></a><a href={`tel:${empresa.telefono}`}><Phone/><strong>{c('telefono')}</strong><span>{marca('telefono')}</span></a><a href={enlaceCorreo()} target="_blank" rel="noopener noreferrer"><Mail/><strong>{c('correo')}</strong><span>{marca('correo')}</span></a></div><section className="contacto-redes" aria-labelledby="contacto-redes-titulo"><div><p className="etiqueta">{c('redesEtiqueta')}</p><h2 id="contacto-redes-titulo">{c('redesTitulo')}</h2><p>{c('redesTexto')}</p></div><div className="contacto-redes-enlaces"><a href={empresa.instagram} target="_blank" rel="noopener noreferrer" title={n('nuevaPestana')}><Instagram size={21}/><span><strong>{c('instagram')}</strong><small>{c('instagramCuenta')}</small></span><ArrowUpRight size={17}/></a><a href={empresa.facebook} target="_blank" rel="noopener noreferrer" title={n('nuevaPestana')}><Facebook size={21}/><span><strong>{c('facebook')}</strong><small>{c('facebookCuenta')}</small></span><ArrowUpRight size={17}/></a></div></section><div className="ubicacion-grid"><div className="ubicacion-foto"><Image src="/imagenes/oficina.webp" alt={t('nosotrosAlt')} fill sizes="(max-width: 760px) 100vw, 45vw"/></div><div><MapPin size={28}/><h2>{c('visita')}</h2><p>{marca('direccion')}</p><div className="ubicacion-acciones"><a className="boton boton-azul" href={empresa.mapa} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>{c('googleMaps')}</a><a className="boton boton-contorno" href={empresa.waze} target="_blank" rel="noopener noreferrer"><Navigation size={17}/>{c('waze')}</a></div></div></div></section></main>;
}
