import {test,expect} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import {randomBytes,createHash} from 'node:crypto';
test.describe.configure({mode:'serial'});
for(const idioma of ['es','en'])test(`altas visibles y errores precisos ${idioma}`,async({page,context})=>{
 test.skip(process.env.SG_TEST_ALTAS!=='1','Solo con servidor local aislado');
 test.setTimeout(90000);
 const rutas=['cuenta','catalogo','contenido'].map(n=>`.privado/admin-local/${n}.json`);
 const originales=await Promise.all(rutas.map(p=>readFile(p,'utf8')));
 const cuenta=JSON.parse(originales[0]);const token=randomBytes(32).toString('hex');
 cuenta.sesiones.push({hash:createHash('sha256').update(token).digest('hex'),vence:Date.now()+120000});
 await writeFile(rutas[0],JSON.stringify(cuenta),{mode:0o600});
 await context.addCookies([{name:'sg-admin-local',value:token,domain:'127.0.0.1',path:'/'},{name:'sg-idioma',value:idioma,domain:'127.0.0.1',path:'/'}]);
 const es=idioma==='es';
 const guardar=()=>page.locator('.admin-actions button').first().click();
 try{
  await page.goto('/panel/catalogo');
  await expect(page.locator('.panel-navegacion a[href="/panel/catalogo"]')).toHaveAttribute('aria-current','page');
  await expect(page.locator('main:visible .admin-producto-fila')).toHaveCount(20);
  const primera=await page.locator('main:visible .admin-producto-fila').first().innerText();
  await page.locator('.admin-paginacion select').first().selectOption('2');
  await expect(page.locator('main:visible .admin-producto-fila')).toHaveCount(20);
  await expect(page.locator('main:visible .admin-producto-fila').first()).not.toHaveText(primera);
  const codigo=JSON.parse(originales[1]).contenido.productos[0].codigoFabricante;
  await page.locator('input[type=search]').fill(codigo);
  await expect(page.locator('main:visible .admin-producto-fila').first()).toContainText(codigo);
  await page.locator('input[type=search]').fill('');
  await page.locator('.admin-producto-fila button').first().click();
  await expect(page.locator('main:visible .admin-producto-fila')).toHaveCount(0);
  await expect(page.locator('.admin-editor-indice a')).toHaveCount(5);
  const precios=page.locator('.admin-producto-seccion[id$="-precios"] input[type=number]');
  const precioOriginal=await precios.first().inputValue();
  await precios.first().fill('100000');
  await expect(page.locator('.admin-precio-resumen')).toContainText('100');
  await precios.first().fill(precioOriginal);
  const nombre=page.locator('.admin-producto-editor').getByRole('textbox',{name:es?'Nombre (ES)':'Name (ES)',exact:true});
  const previo=await nombre.inputValue();
  await nombre.fill(previo+' UX');await guardar();
  await expect(page.locator('.admin-actions [role=status]')).toHaveText(es?'Cambios guardados.':'Changes saved.');
  await nombre.fill(previo+' SIN GUARDAR');
  page.once('dialog',d=>d.accept());
  await page.locator('.admin-actions button').nth(1).click();
  await page.locator('.admin-producto-fila button').first().click();
  await expect(nombre).toHaveValue(previo+' UX');
  await nombre.fill(previo);await guardar();
  await expect(page.locator('.admin-actions [role=status]')).toHaveText(es?'Cambios guardados.':'Changes saved.');
  await expect(page.locator('.admin-editor-seccion').first()).not.toHaveAttribute('open');
  await page.screenshot({path:'evidencias/admin-ux-'+idioma+'-'+test.info().project.name+'.png',fullPage:true});
  await page.locator('.admin-tabs button').nth(1).click();
  await page.locator('.admin-lista-cabecera button').click();
  const categoria=page.locator('.admin-item').first();
  await expect(categoria.locator('input').first()).toBeFocused();
  await categoria.locator('input').nth(0).fill('Categoría QA');
  await categoria.locator('input').nth(1).fill('QA category');
  await guardar();await expect(page.locator('.admin-actions [role=status]')).toHaveText(es?'Cambios guardados.':'Changes saved.');
  await page.locator('.admin-tabs button').first().click();
  await page.locator('.admin-lista-cabecera button').click();
  const nuevo=page.locator('.admin-producto-editor');
  await expect(nuevo).toBeVisible();
  await expect(nuevo.locator('input').first()).toBeFocused();
  await page.locator('.admin-tabs button').nth(2).click();
  await guardar();
  await expect(page.locator('.admin-validacion')).toContainText(es?'Productos':'Products');
  await page.locator('.admin-validacion button').first().click();
  await expect(nuevo).toBeVisible();
  await nuevo.getByRole('textbox',{name:es?'Nombre (ES)':'Name (ES)',exact:true}).fill('Producto QA');
  await nuevo.getByRole('textbox',{name:es?'Nombre (EN)':'Name (EN)',exact:true}).fill('QA product');
  await nuevo.getByRole('textbox',{name:es?'Descripción (ES)':'Description (ES)',exact:true}).fill('Descripción QA');
  await nuevo.getByRole('textbox',{name:es?'Descripción (EN)':'Description (EN)',exact:true}).fill('QA description');
  await guardar();await expect(page.locator('.admin-actions [role=status]')).toHaveText(es?'Cambios guardados.':'Changes saved.');
  await page.reload();await page.locator('main:visible .admin-lista-filtros select').last().selectOption('borradores');await expect(page.locator('main:visible .admin-producto-fila').first()).toContainText(es?'Producto QA':'QA product');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await page.goto('/panel/contenido');
  await expect(page.locator('.panel-navegacion a[href="/panel/contenido"]')).toHaveAttribute('aria-current','page');
  await page.locator('fieldset > button').first().click();
  await expect(page.locator('details.admin-item').last()).toHaveAttribute('open','');
  await expect(page.locator('details.admin-item').last().locator('input').first()).toBeFocused();
  page.once('dialog',d=>d.accept());await page.locator('details.admin-item').last().locator(':scope > button').click();
  await page.locator('.admin-tabs button').nth(1).click();
  await expect(page.locator('details.admin-item')).toHaveCount(30);
  await page.getByRole('button',{name:es?'Mostrar más textos':'Show more text entries',exact:true}).click();
  await expect(page.locator('details.admin-item')).toHaveCount(60);
  await page.locator('input[type=search]').fill('Entrada.descripcion');
  await page.locator('details summary').click();await page.locator('details textarea').first().fill('Texto de prueba QA');
  await guardar();await expect(page.locator('.admin-actions [role=status]')).toHaveText(es?'Cambios guardados.':'Changes saved.');
  await page.goto('/');await context.addCookies([{name:'sg-idioma',value:'es',domain:'127.0.0.1',path:'/'}]);await page.reload();await expect(page.locator('main')).toContainText('Texto de prueba QA');
 }finally{await Promise.all(rutas.map((p,i)=>writeFile(p,originales[i],{mode:0o600})));}
});
