'use client';
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {traducir,type CatalogoPublico} from '@/lib/catalogo-modelo';
import {prepararPedidoAsesorado} from '@/app/panel/pedidos/asesoria-acciones';
export function PrepararAsesoria({id,articulos,productos}:{id:string;articulos:{producto:CatalogoPublico['productos'][number];cantidad:number}[];productos:CatalogoPublico['productos']}){
 const t=useTranslations('AsesoriaAdmin'),l=useLocale();const [filas,setFilas]=useState(articulos.map(x=>({id:x.producto.id,cantidad:x.cantidad,precio:x.producto.precio??0})));const [nuevo,setNuevo]=useState('');
 return <form action={prepararPedidoAsesorado} className="asesoria-admin-form"><input type="hidden" name="id" value={id}/>{filas.map((x,i)=><div className="asesoria-admin-linea" key={x.id}><input type="hidden" name="producto" value={x.id}/><strong>{traducir(productos.find(p=>p.id===x.id)?.nombre??articulos.find(a=>a.producto.id===x.id)!.producto.nombre,l)}</strong><label>{t('cantidad')}<input type="number" name="cantidad" min="1" max="99" required value={x.cantidad} onChange={e=>setFilas(f=>f.map((v,j)=>j===i?{...v,cantidad:Number(e.target.value)}:v))}/></label><label>{t('precio')}<input type="number" name="precio" min="1" max="100000000" step="1" required value={x.precio} onChange={e=>setFilas(f=>f.map((v,j)=>j===i?{...v,precio:Number(e.target.value)}:v))}/></label><button type="button" className="boton boton-contorno" onClick={()=>setFilas(f=>f.filter((_,j)=>i!==j))}>{t('quitar')}</button></div>)}<div className="asesoria-admin-agregar"><label>{t('producto')}<select value={nuevo} onChange={e=>setNuevo(e.target.value)}><option value="">{t('elegir')}</option>{productos.filter(p=>!filas.some(f=>f.id===p.id)).map(p=><option key={p.id} value={p.id}>{traducir(p.nombre,l)}</option>)}</select></label><button type="button" className="boton boton-contorno" disabled={!nuevo||filas.length>=30} onClick={()=>{const p=productos.find(p=>p.id===nuevo)!;setFilas(f=>[...f,{id:p.id,cantidad:1,precio:p.precio??0}]);setNuevo('');}}>{t('agregar')}</button></div><label className="asesoria-admin-confirmar"><input type="checkbox" name="confirmado" required/>{t('confirmar')}</label><button className="boton boton-azul" disabled={!filas.length}>{t('preparar')}</button><p>{t('vence')}</p></form>;
}
